http://localhost:3000/personas

###########
http://localhost:3000/personas/david

###########

POST http://localhost:3000/personas
content-type: application/json

{
    "nombre": "marta",
    "apellidos": "perez",
    "edad":"30"
}
