http://localhost:3000/personas

###########

http://localhost:3000/personas

###########

POST http://localhost:3000/login
content-type: application/json

{
    "nombre": "cecilio",
    "clave": "123456"
}


###########
http://localhost:3000/personas?nombre=dan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlY2lsaW8iLCJpYXQiOjE2ODk5MjQ2ODYsImV4cCI6MTY4OTkzMTg4Nn0.snDmN6Rp-feuZ3mljU6MwKfHC0WgF56chYka8FZQsjc